version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    networks:
      - mynetwork

  redis:
    image: redis:latest
    networks:
      - mynetwork

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_PASSWORD: qwerty
    volumes:
      - db_mysql_data:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  db_mysql_data:

networks:
  mynetwork:
